version: "3.5"

services:
  api1:
    # image: arkanttus/rinha-backend-2024:latest
    &api
    build: ./
    container_name: api1
    hostname: api1
    restart: on-failure
    ports:
      - "3001:3000"
    environment:
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 3000
      DB_NAME: "rinha"
      DB_USERNAME: "rinha"
      DB_PASS: "rinha"
      DB_HOSTNAME: "db"
      DB_PORT: 5432
      DB_POOL_SIZE: 50
      OTEL_ENDPOINT: "http://otel-collector:4318"
    # healthcheck:
    #   test: curl --fail http://localhost:3000/ || exit 1
    #   interval: 40s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 60s
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130MB"

  api2:
    # Essa sintaxe reusa o que foi declarado em 'api1'.
    <<: *api
    container_name: api2
    hostname: api2
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "10MB"

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db_logs:/var/log/postgresql
    command: "postgres -c config_file='/etc/postgresql/postgresql.conf'"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # ulimits:
    #   nofile:
    #     soft: 100000
    #     hard: 100000
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "310MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

volumes:
  database:
